kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: k8s-security-lab
networking:
  # Mantido por compatibilidade; usa mesma base de cluster-calico.yaml.
  disableDefaultCNI: true
  podSubnet: "192.168.0.0/16"
nodes:
  - role: control-plane
  - role: worker
  - role: worker
