apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-secure-sa
  namespace: k8s-security-lab
# Esta aplicacao nao precisa consumir a API do Kubernetes.
# Portanto, o token da ServiceAccount nao deve ser montado automaticamente.
automountServiceAccountToken: false
