apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-reader-sa
  namespace: k8s-security-lab
# Esta conta sera usada em exemplos de RBAC para leitura limitada de Pods.
# Mantemos o automount habilitado para cenarios didaticos de acesso autenticado a API.
automountServiceAccountToken: true
